@TM:1366716892
@N:  :"":0:0:0:-1|Running in 64-bit mode
@N:  :"":0:0:0:-1|: Running Verilog Compiler in System Verilog mode
@N:  :"":0:0:0:-1|: Running Verilog Compiler in Multiple File Compilation Unit mode
@TM:1366716898
@N: BN225 :"":0:0:0:-1|Writing default property annotation file H:\work\Part3\P3-Project\Code\Synplify\rev_1\Main.sap.
@TM:1366716909
@N: FX164 :"":0:0:0:-1|The option to pack flops in the IOB has not been specified 
@TM:1366716898
@W: FX474 :"":0:0:0:-1|User-specified initial value defined for some sequential elements which can prevent optimum synthesis results from being achieved. 
@TM:1366716909
@N: FX493 :"":0:0:0:-1|Applying initial value "00" on instance norm.state[1:0] 
@N: MF248 :"":0:0:0:-1|Running in 64-bit mode.
@N: MF248 :"":0:0:0:-1|Running in 64-bit mode.
@N: MF257 :"":0:0:0:-1|Gated clock conversion enabled 
@N: MF257 :"":0:0:0:-1|Gated clock conversion enabled 
@TM:1366721958
@N: MF322 :"":0:0:0:-1|Retiming summary: 0 registers retimed to 2 
@TM:1366716909
@N: MF333 :"":0:0:0:-1|Generated clock conversion enabled, but no generated clocks found in design 
@N: MF546 :"":0:0:0:-1|Generated clock conversion enabled 
@N: MF546 :"":0:0:0:-1|Generated clock conversion enabled 
@N: MT320 :"":0:0:0:-1|Timing report estimates place and route data. Please look at the place and route timing report for final timing.
@N: MT322 :"":0:0:0:-1|Clock constraints cover only FF-to-FF paths associated with the clock.
@W: MT420 :"":0:0:0:-1|Found inferred clock top_level|clk with period 20.00ns. Please declare a user-defined clock on object "p:clk"
@TM:1366716892
@N: CG364 :"H:\work\Part3\P3-Project\Code\Synplify\modules\all_s_data.sv":4:7:4:16|Synthesizing module s_data_rom
@TM:1366719457
@N: FA239 :"h:\work\part3\p3-project\code\synplify\modules\all_s_data.sv":17:2:17:5|M
@N: FA239 :"h:\work\part3\p3-project\code\synplify\modules\all_s_data.sv":17:2:17:5|M
@N: FA239 :"h:\work\part3\p3-project\code\synplify\modules\all_s_data.sv":17:2:17:5|M
@N: FA239 :"h:\work\part3\p3-project\code\synplify\modules\all_s_data.sv":17:2:17:5|M
@N: FA239 :"h:\work\part3\p3-project\code\synplify\modules\all_s_data.sv":17:2:17:5|M
@N: FA239 :"h:\work\part3\p3-project\code\synplify\modules\all_s_data.sv":17:2:17:5|M
@N: FA239 :"h:\work\part3\p3-project\code\synplify\modules\all_s_data.sv":17:2:17:5|M
@N: FA239 :"h:\work\part3\p3-project\code\synplify\modules\all_s_data.sv":17:2:17:5|M
@N: FA239 :"h:\work\part3\p3-project\code\synplify\modules\all_s_data.sv":17:2:17:5|M
@N: FA239 :"h:\work\part3\p3-project\code\synplify\modules\all_s_data.sv":17:2:17:5|M
@N: FA239 :"h:\work\part3\p3-project\code\synplify\modules\all_s_data.sv":17:2:17:5|M
@N: FA239 :"h:\work\part3\p3-project\code\synplify\modules\all_s_data.sv":17:2:17:5|M
@N: FA239 :"h:\work\part3\p3-project\code\synplify\modules\all_s_data.sv":17:2:17:5|M
@N: FA239 :"h:\work\part3\p3-project\code\synplify\modules\all_s_data.sv":17:2:17:5|M
@N: FA239 :"h:\work\part3\p3-project\code\synplify\modules\all_s_data.sv":17:2:17:5|M
@N: FA239 :"h:\work\part3\p3-project\code\synplify\modules\all_s_data.sv":17:2:17:5|M
@N: FA239 :"h:\work\part3\p3-project\code\synplify\modules\all_s_data.sv":17:2:17:5|M
@N: FA239 :"h:\work\part3\p3-project\code\synplify\modules\all_s_data.sv":17:2:17:5|M
@N: FA239 :"h:\work\part3\p3-project\code\synplify\modules\all_s_data.sv":17:2:17:5|M
@N: FA239 :"h:\work\part3\p3-project\code\synplify\modules\all_s_data.sv":17:2:17:5|M
@N: FA239 :"h:\work\part3\p3-project\code\synplify\modules\all_s_data.sv":17:2:17:5|M
@N: FA239 :"h:\work\part3\p3-project\code\synplify\modules\all_s_data.sv":17:2:17:5|M
@N: FA239 :"h:\work\part3\p3-project\code\synplify\modules\all_s_data.sv":17:2:17:5|M
@N: MO106 :"h:\work\part3\p3-project\code\synplify\modules\all_s_data.sv":17:2:17:5|M
@N: MO106 :"h:\work\part3\p3-project\code\synplify\modules\all_s_data.sv":17:2:17:5|M
@N: MO106 :"h:\work\part3\p3-project\code\synplify\modules\all_s_data.sv":17:2:17:5|M
@N: MO106 :"h:\work\part3\p3-project\code\synplify\modules\all_s_data.sv":17:2:17:5|M
@N: MO106 :"h:\work\part3\p3-project\code\synplify\modules\all_s_data.sv":17:2:17:5|M
@N: MO106 :"h:\work\part3\p3-project\code\synplify\modules\all_s_data.sv":17:2:17:5|M
@N: MO106 :"h:\work\part3\p3-project\code\synplify\modules\all_s_data.sv":17:2:17:5|M
@N: MO106 :"h:\work\part3\p3-project\code\synplify\modules\all_s_data.sv":17:2:17:5|M
@N: MO106 :"h:\work\part3\p3-project\code\synplify\modules\all_s_data.sv":17:2:17:5|M
@N: MO106 :"h:\work\part3\p3-project\code\synplify\modules\all_s_data.sv":17:2:17:5|M
@N: MO106 :"h:\work\part3\p3-project\code\synplify\modules\all_s_data.sv":17:2:17:5|M
@N: MO106 :"h:\work\part3\p3-project\code\synplify\modules\all_s_data.sv":17:2:17:5|M
@N: MO106 :"h:\work\part3\p3-project\code\synplify\modules\all_s_data.sv":17:2:17:5|M
@N: MO106 :"h:\work\part3\p3-project\code\synplify\modules\all_s_data.sv":17:2:17:5|M
@N: MO106 :"h:\work\part3\p3-project\code\synplify\modules\all_s_data.sv":17:2:17:5|M
@N: MO106 :"h:\work\part3\p3-project\code\synplify\modules\all_s_data.sv":17:2:17:5|M
@N: MO106 :"h:\work\part3\p3-project\code\synplify\modules\all_s_data.sv":17:2:17:5|M
@N: MO106 :"h:\work\part3\p3-project\code\synplify\modules\all_s_data.sv":17:2:17:5|M
@N: MO106 :"h:\work\part3\p3-project\code\synplify\modules\all_s_data.sv":17:2:17:5|M
@N: MO106 :"h:\work\part3\p3-project\code\synplify\modules\all_s_data.sv":17:2:17:5|M
@N: MO106 :"h:\work\part3\p3-project\code\synplify\modules\all_s_data.sv":17:2:17:5|M
@N: MO106 :"h:\work\part3\p3-project\code\synplify\modules\all_s_data.sv":17:2:17:5|M
@N: MO106 :"h:\work\part3\p3-project\code\synplify\modules\all_s_data.sv":17:2:17:5|M
@TM:1366716892
@N: CG364 :"H:\work\Part3\P3-Project\Code\Synplify\modules\gdp.sv":1:0:1:6|Synthesizing module H:\work\Part3\P3-Project\Code\Synplify\modules\gdp.sv_unit
@N: CG364 :"H:\work\Part3\P3-Project\Code\Synplify\modules\gdp.sv":3:7:3:9|Synthesizing module gdp
@TM:1366719457
@W: BN132 :"h:\work\part3\p3-project\code\synplify\modules\gdp.sv":27:0:27:8|M
@W: BN132 :"h:\work\part3\p3-project\code\synplify\modules\gdp.sv":27:0:27:8|M
@W: BN132 :"h:\work\part3\p3-project\code\synplify\modules\gdp.sv":27:0:27:8|M
@N: BN362 :"h:\work\part3\p3-project\code\synplify\modules\gdp.sv":27:0:27:8|M
@TM:1366719440
@N: CL135 :"H:\work\Part3\P3-Project\Code\Synplify\modules\gdp.sv":27:0:27:8|M
@W: CL271 :"H:\work\Part3\P3-Project\Code\Synplify\modules\gdp.sv":27:0:27:8|M
@W: CL279 :"H:\work\Part3\P3-Project\Code\Synplify\modules\gdp.sv":27:0:27:8|M
@TM:1366719457
@N: MF169 :"h:\work\part3\p3-project\code\synplify\modules\gdp.sv":27:0:27:8|M
@N: FA113 :"h:\work\part3\p3-project\code\synplify\modules\gdp.sv":53:22:53:45|M
@N: FX404 :"h:\work\part3\p3-project\code\synplify\modules\gdp.sv":54:20:54:73|M
@TM:1366716892
@N: CG364 :"H:\work\Part3\P3-Project\Code\Synplify\modules\gdp_controller.sv":4:7:4:20|Synthesizing module gdp_controller
@TM:1366719457
@W: MT462 :"h:\work\part3\p3-project\code\synplify\modules\gdp_controller.sv":9:16:9:35|M
@W: MT462 :"h:\work\part3\p3-project\code\synplify\modules\gdp_controller.sv":9:16:9:35|M
@N:  :"h:\work\part3\p3-project\code\synplify\modules\gdp_controller.sv":49:0:49:8|M
@N:  :"h:\work\part3\p3-project\code\synplify\modules\gdp_controller.sv":49:0:49:8|M
@TM:1366716892
@N: CL201 :"H:\work\Part3\P3-Project\Code\Synplify\modules\gdp_controller.sv":49:0:49:8|M
@W: CL249 :"H:\work\Part3\P3-Project\Code\Synplify\modules\gdp_controller.sv":49:0:49:8|M
@A: CL282 :"H:\work\Part3\P3-Project\Code\Synplify\modules\gdp_controller.sv":49:0:49:8|M
@A: CL110 :"H:\work\Part3\P3-Project\Code\Synplify\modules\gdp_controller.sv":126:1:126:2|M
@A: CL110 :"H:\work\Part3\P3-Project\Code\Synplify\modules\gdp_controller.sv":126:1:126:2|M
@A: CL110 :"H:\work\Part3\P3-Project\Code\Synplify\modules\gdp_controller.sv":126:1:126:2|M
@A: CL110 :"H:\work\Part3\P3-Project\Code\Synplify\modules\gdp_controller.sv":126:1:126:2|M
@A: CL110 :"H:\work\Part3\P3-Project\Code\Synplify\modules\gdp_controller.sv":126:1:126:2|M
@A: CL110 :"H:\work\Part3\P3-Project\Code\Synplify\modules\gdp_controller.sv":126:1:126:2|M
@A: CL110 :"H:\work\Part3\P3-Project\Code\Synplify\modules\gdp_controller.sv":126:1:126:2|M
@A: CL110 :"H:\work\Part3\P3-Project\Code\Synplify\modules\gdp_controller.sv":126:1:126:2|M
@A: CL110 :"H:\work\Part3\P3-Project\Code\Synplify\modules\gdp_controller.sv":126:1:126:2|M
@A: CL110 :"H:\work\Part3\P3-Project\Code\Synplify\modules\gdp_controller.sv":126:1:126:2|M
@W: CL118 :"H:\work\Part3\P3-Project\Code\Synplify\modules\gdp_controller.sv":126:1:126:2|M
@W: CL118 :"H:\work\Part3\P3-Project\Code\Synplify\modules\gdp_controller.sv":126:1:126:2|M
@W: CL118 :"H:\work\Part3\P3-Project\Code\Synplify\modules\gdp_controller.sv":126:1:126:2|M
@W: CL118 :"H:\work\Part3\P3-Project\Code\Synplify\modules\gdp_controller.sv":126:1:126:2|M
@W: CL118 :"H:\work\Part3\P3-Project\Code\Synplify\modules\gdp_controller.sv":126:1:126:2|M
@W: CL118 :"H:\work\Part3\P3-Project\Code\Synplify\modules\gdp_controller.sv":126:1:126:2|M
@W: CL118 :"H:\work\Part3\P3-Project\Code\Synplify\modules\gdp_controller.sv":126:1:126:2|M
@W: CL118 :"H:\work\Part3\P3-Project\Code\Synplify\modules\gdp_controller.sv":126:1:126:2|M
@W: CL118 :"H:\work\Part3\P3-Project\Code\Synplify\modules\gdp_controller.sv":126:1:126:2|M
@W: CL118 :"H:\work\Part3\P3-Project\Code\Synplify\modules\gdp_controller.sv":126:1:126:2|M
@W: CL218 :"H:\work\Part3\P3-Project\Code\Synplify\modules\gdp_controller.sv":126:1:126:2|M
@N: CG364 :"H:\work\Part3\P3-Project\Code\Synplify\modules\max.sv":4:7:4:9|Synthesizing module max
@TM:1366719457
@N: BN362 :"h:\work\part3\p3-project\code\synplify\modules\max.sv":14:0:14:8|M
@TM:1366719440
@A: CL282 :"H:\work\Part3\P3-Project\Code\Synplify\modules\max.sv":14:0:14:8|M
@TM:1366716892
@N: CG364 :"H:\work\Part3\P3-Project\Code\Synplify\modules\normaliser.sv":4:7:4:16|Synthesizing module normaliser
@TM:1366719457
@N:  :"h:\work\part3\p3-project\code\synplify\modules\normaliser.sv":30:0:30:8|M
@TM:1366719440
@W: CL189 :"H:\work\Part3\P3-Project\Code\Synplify\modules\normaliser.sv":30:0:30:8|M
@N: CL201 :"H:\work\Part3\P3-Project\Code\Synplify\modules\normaliser.sv":30:0:30:8|M
@W: CL279 :"H:\work\Part3\P3-Project\Code\Synplify\modules\normaliser.sv":30:0:30:8|M
@A: CL282 :"H:\work\Part3\P3-Project\Code\Synplify\modules\normaliser.sv":30:0:30:8|M
@TM:1366716892
@N: CG364 :"H:\work\Part3\P3-Project\Code\Synplify\modules\send.sv":4:7:4:10|Synthesizing module send
@TM:1366719457
@N:  :"h:\work\part3\p3-project\code\synplify\modules\send.sv":30:0:30:8|M
@TM:1366719440
@N: CL201 :"H:\work\Part3\P3-Project\Code\Synplify\modules\send.sv":30:0:30:8|M
@W: CL249 :"H:\work\Part3\P3-Project\Code\Synplify\modules\send.sv":30:0:30:8|M
@A: CL282 :"H:\work\Part3\P3-Project\Code\Synplify\modules\send.sv":30:0:30:8|M
@TM:1366716892
@N: CG364 :"H:\work\Part3\P3-Project\Code\Synplify\modules\sram.sv":4:7:4:10|Synthesizing module sram
@TM:1366719457
@W: BN132 :"h:\work\part3\p3-project\code\synplify\modules\sram.sv":32:0:32:8|M
@A: BN291 :"h:\work\part3\p3-project\code\synplify\modules\sram.sv":32:0:32:8|M
@N: BN362 :"h:\work\part3\p3-project\code\synplify\modules\sram.sv":32:0:32:8|M
@N: BN362 :"h:\work\part3\p3-project\code\synplify\modules\sram.sv":32:0:32:8|M
@TM:1366719440
@N: CL201 :"H:\work\Part3\P3-Project\Code\Synplify\modules\sram.sv":32:0:32:8|M
@W: CL249 :"H:\work\Part3\P3-Project\Code\Synplify\modules\sram.sv":32:0:32:8|M
@A: CL282 :"H:\work\Part3\P3-Project\Code\Synplify\modules\sram.sv":32:0:32:8|M
@A: CL110 :"H:\work\Part3\P3-Project\Code\Synplify\modules\sram.sv":71:2:71:5|M
@W: CL118 :"H:\work\Part3\P3-Project\Code\Synplify\modules\sram.sv":71:2:71:5|M
@W: CL254 :"H:\work\Part3\P3-Project\Code\Synplify\modules\sram.sv":71:2:71:5|M
@TM:1366719457
@N: FX404 :"h:\work\part3\p3-project\code\synplify\modules\sram.sv":71:2:71:5|M
@N: MF578 :"h:\work\part3\p3-project\code\synplify\modules\sram.sv":71:2:71:5|M
@W: MT462 :"h:\work\part3\p3-project\code\synplify\modules\sram.sv":71:2:71:5|M
@W: MT462 :"h:\work\part3\p3-project\code\synplify\modules\sram.sv":71:2:71:5|M
@TM:1366716892
@N: CG364 :"H:\work\Part3\P3-Project\Code\Synplify\modules\top_level.sv":4:7:4:15|Synthesizing module top_level
@N: CL201 :"H:\work\Part3\P3-Project\Code\Synplify\modules\top_level.sv":93:0:93:8|M
@W: CL249 :"H:\work\Part3\P3-Project\Code\Synplify\modules\top_level.sv":93:0:93:8|M
@TM:1366719457
@N:  :"h:\work\part3\p3-project\code\synplify\modules\top_level.sv":162:0:162:5|M
@TM:1366716892
@N: CG364 :"H:\work\Part3\P3-Project\Code\Synplify\modules\uart.sv":4:7:4:10|Synthesizing module uart
@TM:1366719457
@N:  :"h:\work\part3\p3-project\code\synplify\modules\uart.sv":29:0:29:8|M
@TM:1366719440
@A: CL282 :"H:\work\Part3\P3-Project\Code\Synplify\modules\uart.sv":29:0:29:8|M
@TM:1366721958
@N:  :"h:\work\part3\p3-project\code\synplify\modules\uart.sv":59:0:59:8|M
@TM:1366719440
@W: CL190 :"H:\work\Part3\P3-Project\Code\Synplify\modules\uart.sv":59:0:59:8|M
@W: CL190 :"H:\work\Part3\P3-Project\Code\Synplify\modules\uart.sv":59:0:59:8|M
@W: CL260 :"H:\work\Part3\P3-Project\Code\Synplify\modules\uart.sv":59:0:59:8|M
@W: CL279 :"H:\work\Part3\P3-Project\Code\Synplify\modules\uart.sv":59:0:59:8|M
@A: CL282 :"H:\work\Part3\P3-Project\Code\Synplify\modules\uart.sv":59:0:59:8|M
@TM:1366716892
@N: CG364 :"H:\work\Part3\P3-Project\Code\Synplify\modules\uart\baudgen.sv":1:7:1:13|Synthesizing module baudgen
@TM:1366716898
@W: MT529 :"h:\work\part3\p3-project\code\synplify\modules\uart\baudgen.sv":21:0:21:8|M
@TM:1366716892
@N: CG364 :"H:\work\Part3\P3-Project\Code\Synplify\modules\uart\uart_rx.sv":1:7:1:13|Synthesizing module uart_rx
@A: CL282 :"H:\work\Part3\P3-Project\Code\Synplify\modules\uart\uart_rx.sv":21:0:21:8|M
@N: CL201 :"H:\work\Part3\P3-Project\Code\Synplify\modules\uart\uart_rx.sv":40:0:40:8|M
@TM:1366719457
@N:  :"h:\work\part3\p3-project\code\synplify\modules\uart\uart_rx.sv":84:0:84:8|M
@N: BN362 :"h:\work\part3\p3-project\code\synplify\modules\uart\uart_rx.sv":84:0:84:8|M
@TM:1366716892
@N: CG364 :"H:\work\Part3\P3-Project\Code\Synplify\modules\uart\uart_tx.sv":1:7:1:13|Synthesizing module uart_tx
@N: CL201 :"H:\work\Part3\P3-Project\Code\Synplify\modules\uart\uart_tx.sv":20:0:20:8|M
